apiVersion: v1
kind: Service
metadata:
  name: my-awesome-app-service
  namespace: sdp
spec:
  selector:
    app: my-awesome-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer