apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-awesome-app
  namespace: sdp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-awesome-app
  template:
    metadata:
      labels:
        app: my-awesome-app
    spec:
      containers:
      - name: my-awesome-app
        image: natalicot/my_awsome_app:1.0.3
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"


