apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  namespace: sdp
data:
  example.property: "Hello, world!"

---

apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: sdp
spec:
  containers:
  - name: example-container
    image: busybox
    command: ["sh", "-c"]
    args: ["while true; do echo hello; sleep 10;done"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config  # The directory where the ConfigMap will be mounted
  volumes:
  - name: config-volume
    configMap:
      name: example-config  # The name of the ConfigMap
