apiVersion: v1
kind: Pod
metadata:
  name: failure-pod
  namespace: sdp
spec:
  containers:
  - name: failure-container
    image: busybox
    command: ['sh', '-c', 'echo $(date -u -D %s -d $(( $(date +%s) + 10800 ))) - The container is going to fail now; exit 1']
