#!/bin/bash

# This is a kubectl plugin to extend kubectl functionality.
# Maintainer: Natali Cutic

function check_cowsay {
  if command -v cowsay &> /dev/null
  then
    ANIMAL=$(ls /usr/share/cowsay/cows/ | shuf -n 1 | cut -d. -f1 | sed 's/[^a-zA-Z0-9_-]*//g')
    cowsay -f $ANIMAL "Welcome to SDP 2023!" 
  else
    echo "Welcome to SDP 2023!"
  fi
}

function print_help {
  echo "Usage: kubectl sdp <command>"
  echo ""
  echo "Available commands:"
  echo "  set-ns    Set the current namespace to 'sdp'"
  echo "  debug     Run debug on the pod starting with 'no-sh-deployment'"
  echo "  welcome   Print a welcome message"
  echo "  help      Print this help message"
  echo ""
  echo "Maintainer: Natali Cutic"
}

case $1 in
set-ns)
    kubectl config set-context --current --namespace=sdp
    echo "Successfully changed namespace to 'sdp'. It's like finding the perfect spot on the couch - now you are exactly where you need to be! 🛋️"
    ;;
debug)
    POD_NAME=$(kubectl get pods --namespace sdp --no-headers -o custom-columns=":metadata.name" | grep '^no-sh-deployment')
    kubectl debug $POD_NAME -it --image=busybox --target=container
    ;;
welcome)
    check_cowsay
    ;;
help)
    print_help
    ;;
*)
    echo "Invalid command. Please use 'kubectl sdp help' to see the available commands."
    ;;
esac
