apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-sh-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: container
        image: natalicot/sleep-node-app:1.0.0
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: my-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  VARIABLE_1: "value1"
  VARIABLE_2: "value2"
